### ISSUE TITLE
Add cursor line highlight

### ISSUE THREAD

**Issue by vajahath** [RobinBoers/frontend-delight-vscode#2]
I love this theme. :star: 
Please add cursor line highlight. Easier to identify where am I working now.

Eg: cursor highlight from default Kimbie Dark. 
![Screenshot from 2022-02-04 10-58-45](https://user-images.githubusercontent.com/12165822/152477405-812b5ccc-a625-4f87-9c72-150b41ed4440.png)

Frontend delight enhanced.
![Screenshot from 2022-02-04 10-59-15](https://user-images.githubusercontent.com/12165822/152477526-e79550ab-ba06-48a4-9d1b-de3f7e222173.png)

Also a thought: can the background color can be a bit more dark? It could pop the text out of it.

**Comment by RobinBoers** [comment]
Glad you like it :)

I pushed a commit with the new line highlight and another sub-theme called "Dark"
